# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JamChat' do

    # Facebook
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
    
    # Parse
    pod 'ParseFacebookUtilsV4'
	pod 'Parse'
    pod 'ParseUI'
    
    # Audio
    pod 'AudioKit'

  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JamChat

end
