# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JamChat' do

  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JamChat:

    # Facebook
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'

    # Parse
    pod 'ParseFacebookUtilsV4'
    pod 'Parse'
    pod 'ParseUI'

    # Audio
    pod 'AudioKit'

    #Networking
    pod 'AFNetworking'

    # UI
    pod 'RAMReel'
    pod 'RBBAnimation'
    pod 'EasyAnimation'
    pod 'FDWaveformView'
    pod 'KTCenterFlowLayout'
    pod 'XLPagerTabStrip'
    pod 'CircleMenu'
    pod 'IntervalSlider'
    pod 'DGElasticPullToRefresh'

end
